services:
  web:
    image: "${APP_NAME}-web:${APP_ENV}"
    container_name: "${APP_NAME}-web"
    user: "${LOCAL_UID}:${LOCAL_GID}"
    environment:
      HOST_PORT: "${HOST_PORT}"
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
      DB_DATABASE: "${DB_DATABASE}"
      DB_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    build:
      context: .
      dockerfile: Dockerfiles/web/Dockerfile
      target: ${APP_ENV}
      args:
        APP_NAME: ${APP_NAME}
    ports:
      - "${HOST_PORT}:80"
    volumes:
      - ./${APP_NAME}:/var/www/html/${APP_NAME}
    depends_on:
      - db
    networks:
      - app_network
    extra_hosts:
      - "host.${APP_NAME}.internal:host-gateway"

  db:
    image: "${APP_NAME}-db:${APP_ENV}"
    container_name: "${APP_NAME}-db"
    build:
      context: .
      dockerfile: Dockerfiles/db/Dockerfile
    command:
      - "mysqld"
      - "--port=${DB_PORT}"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - db:/var/lib/mysql
    networks:
      - app_network

volumes:
  db:
    name: "${APP_NAME}-volumes-db"

networks:
  app_network:
    name: "${APP_NAME}-network"
    driver: bridge
